export const myProjects = [
  {
    projectTitle: "Fast Pizza",
    category: "react",
    imgPath: "/images/pizza.png",
    liveDemo: "https://fast-pizza-roan.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/fast-pizza",
  },
  {
    projectTitle: "Natours",
    category: "html&css",
    imgPath: "/images/natours.png",
    liveDemo: "https://natours-olive-five.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/Natours",
  },
  {
    projectTitle: "watches",
    category: "javascript",
    imgPath: "/images/Watches.png",
    liveDemo: "https://watches-shopping.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/watches-shopping",
  },
  {
    projectTitle: "coffee shop",
    category: "html&css",
    imgPath: "/images/Coffee.png",
    liveDemo: "https://coffee-ashen-iota.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/coffee-shop",
  },
  {
    projectTitle: "World Wise",
    category: "react",
    imgPath: "/images/WorldWise.png",
    liveDemo: "https://world-wise-ruby.vercel.app",
    githubRepo: "https://github.com/Amr-Kamall/World-Wise",
  },
  {
    projectTitle: "movies",
    category: "react",
    imgPath: "/images/movie.png",
    liveDemo: "https://use-pop-corn-zeta.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/UsePopcorn",
  },
  {
    projectTitle: "Dashboard",
    category: "react",
    imgPath: "/images/dashboard.png",
    liveDemo: "https://dashboard-bay-chi.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/dashboard",
  },

  {
    projectTitle: "Crud",
    category: "javascript",
    imgPath: "/images/crud.png",
    liveDemo: "https://crud-hazel-delta.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/Crud",
  },
  {
    projectTitle: "Nike",
    category: "javascript",
    imgPath: "/images/Nike.png",
    liveDemo: "https://nike-store-henna.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/Nike-Store",
  },

  {
    projectTitle: "Covid-19",
    category: "bootstrab",
    imgPath: "/images/covid.png",
    liveDemo: "https://covid-19-bay.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/covid-19",
  },
  {
    projectTitle: "Level",
    category: "bootstrab",
    imgPath: "/images/Level.png",
    liveDemo: "https://level-company.vercel.app/",
    githubRepo: "https://github.com/Amr-Kamall/level-company",
  },
];
